config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "photos#index"

  resources :accounts, only: [:show]

  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string           not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true

  has_one :profile, dependent: :destroy

  def prepare_profile
    profile || build_profile
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: '更新完了'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/show.html.haml
= render 'commons/profile', user: @user 

app/views/commons/_profile.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_image
      = label_tag :avatar do
        - if user.avatar_image
          = image_tag user.avatar_image, class: 'avatar'
          = file_field_tag :avatar, class: 'uploader', style: 'display:none'
        - else
          = image_tag 'Ellipse.png', class: 'avatar'
          = file_field_tag :avatar, class: 'uploader', style: 'display:none'          
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          #{user.display_name}
        .profilePage_user_actionButton
          - if user == current_user
            = link_to 'Edit', edit_profile_path

= javascript_pack_tag 'profile'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title InstagramApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete'}
    = yield

app/views/photos/index.html.haml
- if user_signed_in?
  = link_to 'ユーザー詳細', account_path(current_user)

app/views/profiles/edit.html.haml
.container
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= massage

  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div 
      = f.label :avatar, 'Avatar'
    %div
      = f.file_field :avatar
    %div 
      = f.label :name, 'Name'
    %div
      = f.text_field :name, class: 'text'

    = f.submit '保存', class: 'btn-primary'

app/views/profiles/show.html.haml
= render 'commons/profile', user: current_user